### ISSUE TITLE
Doesn't work on Android 

### ISSUE THREAD

**Issue by Ahmed-Imam** [alizahid/location-picker-demo#1]
It is working like a charm on IOS, unfortunately the fake marker is not showing on Android. 
its showing for one sec and its getting cover by the map i think ?

**Comment by hefejeff** [comment]
I am facing the same issue.  Has anyone found a solution?

**Comment by Ahmed-Imam2** [comment]
[check this answer in stackoverflow](https://stackoverflow.com/questions/54379272/react-native-maps-custom-marker-android/54386944#54386944)

**Comment by hefejeff** [comment]
Thank you very much for taking time to respond.  I still can't get it to show up on android.  I noticed that your css starts with [![ and ends with },`][1]][1].  Could you please point me in the right direction to understand this?

**Comment by Ahmed-Imam** [comment]
can u share your code ? so we can identify the issue.

**Comment by hefejeff** [comment]
`<MapView
			provider={PROVIDER_GOOGLE}
			style={styles.map}
			mapType={'satellite'}
			initialRegion={region}
			onRegionChangeComplete={this.onRegionChange}
			showsUserLocation={true}
			followsUserLocation={true}
			loadingEnabled={true}
			loadingIndicatorColor="#666666"
			loadingBackgroundColor="#eeeeee"
			>
				{this.state.overlay1.image && this.state.overlay1.image !== undefined ? <MapView.Overlay
				bounds={this.state.overlay1.bounds}
				image={{uri: this.state.overlay1.image}}
				zindex={2}
				/> : null}
				{!this.state.overlay1.image && this.state.isReady && polygons ? polygons.map(polygon =>
				(
				<MapView.Polygon
					key={polygon.id}
					coordinates={polygon.coordinates}
					fillColor={this.state.polygonFillColor}
					strokeColor={polygon.zonePolyLineColor}
					strokeWidth={polygon.zonePolyWidth}
					/>
				),
				) : null}

				{!this.state.overlay1.image && lineArray ? lineArray.map(line =>
				(
				<MapView.Polyline
					key={line.id}
					lineJoin={'miter'}
					coordinates={line.coordinates}
					strokeColor={line.zonePolyLineColor}
					strokeWidth={line.zonePolyWidth}
				/>
				),
				) : null}	

				{!this.state.overlay1.image && this.state.isReady && markers ? markers.map(marker =>
				(
				<MapView.Marker
					key={marker.id}
					coordinate={{
					latitude: parseFloat(marker.zonePinCoords[1]),
					longitude: parseFloat(marker.zonePinCoords[0])
					}}
					title={marker.zoneName}
					description={marker.zoneDesc}>
					<View style={styles.markerBox}>
						<View style={styles.markerBox2}>
							<Text style={styles.markerBoxText}> 
								{marker.zoneName} 
							</Text>
						</View>
					</View>
					<MapView.Callout>
						<View style={styles.calloutBox}>
						<Text style={styles.markerBoxTitleText}>
							Zone {this.state.language === 'English' ? marker.zoneName : marker.zoneNameEs}
						</Text>
						<Text style={styles.calloutBoxText}>
							{ this.state.language === 'English' ? marker.zoneDesc: marker.zoneDescEs}
						</Text>
						</View>
					</MapView.Callout>
				</MapView.Marker>
				),
			) : null}
			{!this.state.overlay1.image && this.state.isReady && lineMarkers.length > 0 && lineMarkers[0].zonePinCoords ? lineMarkers.map(marker =>
				(
				<MapView.Marker
					key={marker.id}
					coordinate={{
					latitude: parseFloat(marker.zonePinCoords[1]),
					longitude: parseFloat(marker.zonePinCoords[0])
					}}
					title={marker.zoneName}
					description={marker.zoneDesc}>
					<View style={styles.markerBox}>
						<View style={styles.markerBox2}>
							<Text style={styles.markerBoxText}> 
								{marker.zoneName} 
							</Text>
						</View>
					</View>
					<MapView.Callout>
						<View style={styles.calloutBox}>
						<Text style={styles.markerBoxTitleText}>
							Zone {this.state.language === 'English' ? marker.zoneName : marker.zoneNameEs}
						</Text>
						<Text style={styles.calloutBoxText}>
							{ this.state.language === 'English' ? marker.zoneDesc: marker.zoneDescEs}
						</Text>
						</View>
					</MapView.Callout>
				</MapView.Marker>
				),
			) : null}
		</MapView>
		<View style={{ flex:1,
						flexDirection:'row',
						alignItems:'center',
						justifyContent:'center'}} pointerEvents="none">
			<Image style={styles.marker} source={marker} />
		</View>`

`mapContainer: {
		flex:1,
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: 'flex-end',
		alignItems: 'center',
	},
	map: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
	},
	markerFixed: {
		left: '50%',
		marginLeft: -24,
		marginTop: -48,
		position: 'absolute',
		top: '50%',
		zIndex: 2
	},
	marker: {
		height: 48,
		width: 48
	},`

**Comment by hefejeff** [comment]
<View style={styles.mapContainer}>
		<MapView
			provider={PROVIDER_GOOGLE}
			style={styles.map}
			mapType={'satellite'}
			initialRegion={region}
			onRegionChangeComplete={this.onRegionChange}
			showsUserLocation={true}
			followsUserLocation={true}
			loadingEnabled={true}
			loadingIndicatorColor="#666666"
			loadingBackgroundColor="#eeeeee"
			>
</MapView>
		<View style={{ flex:1,
						flexDirection:'row',
						alignItems:'center',
						justifyContent:'center'}} pointerEvents="none">
			<Image style={styles.marker} source={marker} />
		</View>
	</View>

mapContainer: {
		flex:1,
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: 'flex-end',
		alignItems: 'center',
	},
	map: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
	},
	markerFixed: {
		left: '50%',
		marginLeft: -24,
		marginTop: -48,
		position: 'absolute',
		top: '50%',
		zIndex: 2
	},
	marker: {
		height: 48,
		width: 48
	},

**Comment by hefejeff** [comment]
<View style={styles.mapContainer}>
		<MapView
			provider={PROVIDER_GOOGLE}
			style={styles.map}
			mapType={'satellite'}
			initialRegion={region}
			onRegionChangeComplete={this.onRegionChange}
			showsUserLocation={true}
			followsUserLocation={true}
			loadingEnabled={true}
			loadingIndicatorColor="#666666"
			loadingBackgroundColor="#eeeeee">
		</MapView>
		<View style={{ flex:1,
						flexDirection:'row',
						alignItems:'center',
						justifyContent:'center'}} pointerEvents="none">
			<Image style={styles.marker} source={marker} />
		</View>
	</View>

**Comment by hefejeff** [comment]
`<View style={styles.mapContainer}>
		<MapView
			provider={PROVIDER_GOOGLE}
			style={styles.map}
			mapType={'satellite'}
			initialRegion={region}
			onRegionChangeComplete={this.onRegionChange}
			showsUserLocation={true}
			followsUserLocation={true}
			loadingEnabled={true}
			loadingIndicatorColor="#666666"
			loadingBackgroundColor="#eeeeee"
			>
		</MapView>
		<View style={{ flex:1,
						flexDirection:'row',
						alignItems:'center',
						justifyContent:'center'}} pointerEvents="none">
			<Image style={styles.marker} source={marker} />
		</View>
	</View>`

**Comment by hefejeff** [comment]
<View style={styles.mapContainer}>
		<MapView
			provider={PROVIDER_GOOGLE}
			style={styles.map}
			mapType={'satellite'}
			initialRegion={region}
			onRegionChangeComplete={this.onRegionChange}
			showsUserLocation={true}
			followsUserLocation={true}
			loadingEnabled={true}
			loadingIndicatorColor="#666666"
			loadingBackgroundColor="#eeeeee"
			>
				{this.state.overlay1.image && this.state.overlay1.image !== undefined ? <MapView.Overlay
				bounds={this.state.overlay1.bounds}
				image={{uri: this.state.overlay1.image}}
				zindex={2}
				/> : null}
				{!this.state.overlay1.image && this.state.isReady && polygons ? polygons.map(polygon =>
				(
				<MapView.Polygon
					key={polygon.id}
					coordinates={polygon.coordinates}
					fillColor={this.state.polygonFillColor}
					strokeColor={polygon.zonePolyLineColor}
					strokeWidth={polygon.zonePolyWidth}
					/>
				),
				) : null}

				{!this.state.overlay1.image && lineArray ? lineArray.map(line =>
				(
				<MapView.Polyline
					key={line.id}
					lineJoin={'miter'}
					coordinates={line.coordinates}
					strokeColor={line.zonePolyLineColor}
					strokeWidth={line.zonePolyWidth}
				/>
				),
				) : null}	

				{!this.state.overlay1.image && this.state.isReady && markers ? markers.map(marker =>
				(
				<MapView.Marker
					key={marker.id}
					coordinate={{
					latitude: parseFloat(marker.zonePinCoords[1]),
					longitude: parseFloat(marker.zonePinCoords[0])
					}}
					title={marker.zoneName}
					description={marker.zoneDesc}>
					<View style={styles.markerBox}>
						<View style={styles.markerBox2}>
							<Text style={styles.markerBoxText}> 
								{marker.zoneName} 
							</Text>
						</View>
					</View>
					<MapView.Callout>
						<View style={styles.calloutBox}>
						<Text style={styles.markerBoxTitleText}>
							Zone {this.state.language === 'English' ? marker.zoneName : marker.zoneNameEs}
						</Text>
						<Text style={styles.calloutBoxText}>
							{ this.state.language === 'English' ? marker.zoneDesc: marker.zoneDescEs}
						</Text>
						</View>
					</MapView.Callout>
				</MapView.Marker>
				),
			) : null}
			{!this.state.overlay1.image && this.state.isReady && lineMarkers.length > 0 && lineMarkers[0].zonePinCoords ? lineMarkers.map(marker =>
				(
				<MapView.Marker
					key={marker.id}
					coordinate={{
					latitude: parseFloat(marker.zonePinCoords[1]),
					longitude: parseFloat(marker.zonePinCoords[0])
					}}
					title={marker.zoneName}
					description={marker.zoneDesc}>
					<View style={styles.markerBox}>
						<View style={styles.markerBox2}>
							<Text style={styles.markerBoxText}> 
								{marker.zoneName} 
							</Text>
						</View>
					</View>
					<MapView.Callout>
						<View style={styles.calloutBox}>
						<Text style={styles.markerBoxTitleText}>
							Zone {this.state.language === 'English' ? marker.zoneName : marker.zoneNameEs}
						</Text>
						<Text style={styles.calloutBoxText}>
							{ this.state.language === 'English' ? marker.zoneDesc: marker.zoneDescEs}
						</Text>
						</View>
					</MapView.Callout>
				</MapView.Marker>
				),
			) : null}
		</MapView>
		<View style={{ flex:1,
						flexDirection:'row',
						alignItems:'center',
						justifyContent:'center'}} pointerEvents="none">
			<Image style={styles.marker} source={marker} />
		</View>
	</View>

**Comment by hefejeff** [comment]
import React, { Component } from 'react';
import MapView, {PROVIDER_GOOGLE} from 'react-native-maps';

import marker from '../assets/images/mapPointer.bmp';
import {
	Animated, 
	Image, 
	StyleSheet,
	View,
	Dimensions
} from 'react-native';

const {width, height} = Dimensions.get('window');

const ASPECT_RATIO = width / height;
const LATITUDE = 8.679976;
const LONGITUDE = -84.768458;
const LATITUDE_DELTA = 12.00;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
const OVERLAY_TOP_LEFT_COORDINATE1 = [13.000, -92.000];
const OVERLAY_BOTTOM_RIGHT_COORDINATE1 = [1.000, -78.000];

export default class HomeScreen extends Component {
  
  constructor(props) {
    super(props);
    this.state = {
		region: {
			latitude: LATITUDE,
			longitude: LONGITUDE,
			latitudeDelta: LATITUDE_DELTA,
			longitudeDelta: LONGITUDE_DELTA,
			lat: '',
			lon: '',
			dataPoint: '',
			depth: '',
		}
	}
  }
  
	
  onRegionChange = region => {
    this.setState({
      region
	})
	this.mapTapped(region);
  }

  render() {
  return (
	<View style={styles.container}>
	    <View style={styles.mapContainer}>
            <MapView
                provider={PROVIDER_GOOGLE}
                style={styles.map}
                mapType={'satellite'}
                initialRegion={region}
                onRegionChangeComplete={this.onRegionChange}
                showsUserLocation={true}
                followsUserLocation={true}
                loadingEnabled={true}
                loadingIndicatorColor="#666666"
                loadingBackgroundColor="#eeeeee"
                >
            </MapView>
            <View style={{ flex:1,
                            flexDirection:'row',
                            alignItems:'center',
                            justifyContent:'center'}} pointerEvents="none">
                <Image style={styles.marker} source={marker} />
            </View>
	    </View>
	</View>
	);
  }
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
	},
	mapContainer: {
		flex:1,
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: 'flex-end',
		alignItems: 'center',
	},
	map: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
	},
	marker: {
		height: 48,
		width: 48
	}
});

**Comment by hefejeff** [comment]
`import React, { Component } from 'react';
import MapView, {PROVIDER_GOOGLE} from 'react-native-maps';

import marker from '../assets/images/mapPointer.bmp';
import {
	Animated, 
	Image, 
	StyleSheet,
	View,
	Dimensions
} from 'react-native';

const {width, height} = Dimensions.get('window');

const ASPECT_RATIO = width / height;
const LATITUDE = 8.679976;
const LONGITUDE = -84.768458;
const LATITUDE_DELTA = 12.00;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
const OVERLAY_TOP_LEFT_COORDINATE1 = [13.000, -92.000];
const OVERLAY_BOTTOM_RIGHT_COORDINATE1 = [1.000, -78.000];

export default class HomeScreen extends Component {
  
  constructor(props) {
    super(props);
    this.state = {
		region: {
			latitude: LATITUDE,
			longitude: LONGITUDE,
			latitudeDelta: LATITUDE_DELTA,
			longitudeDelta: LONGITUDE_DELTA,
			lat: '',
			lon: '',
			dataPoint: '',
			depth: '',
		}
	}
  }
  
	
  onRegionChange = region => {
    this.setState({
      region
	})
	this.mapTapped(region);
  }

  render() {
  return (
	<View style={styles.container}>
	    <View style={styles.mapContainer}>
            <MapView
                provider={PROVIDER_GOOGLE}
                style={styles.map}
                mapType={'satellite'}
                initialRegion={region}
                onRegionChangeComplete={this.onRegionChange}
                showsUserLocation={true}
                followsUserLocation={true}
                loadingEnabled={true}
                loadingIndicatorColor="#666666"
                loadingBackgroundColor="#eeeeee"
                >
            </MapView>
            <View style={{ flex:1,
                            flexDirection:'row',
                            alignItems:'center',
                            justifyContent:'center'}} pointerEvents="none">
                <Image style={styles.marker} source={marker} />
            </View>
	    </View>
	</View>
	);
  }
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
	},
	mapContainer: {
		flex:1,
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: 'flex-end',
		alignItems: 'center',
	},
	map: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
	},
	marker: {
		height: 48,
		width: 48
	}
});
`

**Comment by Ahmed-Imam** [comment]
I guess you need to rearrange your styling, the map should not be positioned absolute, the view should be, and add an icon or an image inside the view as a fakemarker as follow: 

```
<View style={{flex:1}}>
           <MapView
                region={this.getMapRegion()}
                style={{flex:1}}
                 provider={PROVIDER_GOOGLE}
                 mapType="standard"
                 onRegionChangeComplete={(region) => this.setState({
                      latitude: region.latitude, longitude: region.longitude,
                      latitudeDelta: region.latitudeDelta, longitudeDelta: region.longitudeDelta
                        })} >
                        <View style={{
                            left: '50%',
                            marginLeft: -24,
                            marginTop: -48,
                            position: 'absolute',
                            top: '50%',}}>
                            <Image
                                style={{
                                    resizeMode: 'contain',
                                    height: 60, width: 60,
                            }} source={require('../../assets/fake-marker.png')} />
                        </View>
                    </MapView>
                </View>
```
that should be fine both on ios and android.

**Comment by christopher-18** [comment]
@Ahmed-Imam I used the below styling but , my marker gets hidden below the map. Any workaround for this?
```
const onRegionChange =(region: RegionObject)=>{
    setRegion(region);
    setLatitude(region.latitude);
    setLongitude(region.longitude);
    console.log(region.latitude, region.longitude)
  }

 <MapView
        provider={PROVIDER_GOOGLE}
        style={{height: screenHeight/1.75}}
        region={region}
        zoomEnabled={true}
        minZoomLevel={5}
        onRegionChangeComplete={(region)=>onRegionChange(region)}
        // initialRegion={{latitude:latitude,longitude:longitude,latitudeDelta:latitudeDelta,longitudeDelta:longitudeDelta}}
      >
<View style={{ zIndex:1,left: '50%',marginLeft: -24, marginTop: -48,position: 'absolute',top: '50%'}}>
            <Image style={{height: 35,width: 35,resizeMode:'contain'}} source={FakeMarker} />
        </View>
</MapView>
```
